### ISSUE TITLE
[FEATURE]Support of new k-NN query parameter, expand_nested_docs

### ISSUE THREAD

**Issue by heemin32** [opensearch-project/neural-search#1008]
### Is your feature request related to a problem?
In https://github.com/opensearch-project/k-NN/pull/2283, a new parameter `expand_nested_docs` is added in k-nn query to support multi inner hits. I want it to be supported in neural search.

### What solution would you like?
Support of `expand_nested_docs` parameter in neural search.

### What alternatives have you considered?
Not supporting it.

### Do you have any additional context?
Similar change has been made for a support of ef_search parameter. https://github.com/opensearch-project/neural-search/pull/814

**Comment by bzhangam** [comment]
I'll work on this item.

**Comment by bzhangam** [comment]
Hi @heemin32. I notice that in k-nn query the new field is called **EXPAND_NESTED = "expand_nested_docs"** but here you mention we want to add a new parameter **extend_nested_docs**. Wonder why we intend to use a different name? Should we also use **expand_nested_docs** in neural search for consistency?

**Comment by heemin32** [comment]
> Hi @heemin32. I notice that in k-nn query the new field is called **EXPAND_NESTED = "expand_nested_docs"** but here you mention we want to add a new parameter **extend_nested_docs**. Wonder why we intend to use a different name? Should we also use **expand_nested_docs** in neural search for consistency?

My bad. we will use same name. `expand_nested_docs`
