### ISSUE TITLE
Tests failing due to ml-commons default setting

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/neural-search#103]
Related to https://github.com/opensearch-project/ml-commons/pull/688, our tests fail because the default value for this setting is true: `"plugins.ml_commons.only_run_on_ml_node"`

We will need to update it before running tests with:
```
PUT /_cluster/settings
{
  "persistent" : {
    "plugins.ml_commons.only_run_on_ml_node" : false 
  }
}
```

**Comment by navneet1v** [comment]
Closing this issue as the tests are fixed.
