### ISSUE TITLE
Create custom neural query 

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/neural-search#14]
Create a new query type: "neural". Internally, it will use ML-Commons to take a query string and create a vector from it. From there, it should build a k-NN query.

Interface will look like:
```
GET <index_name>/_search
{
  "size": int,
  "query": {
    "neural": {
      "<vector_field>": {
        "query_text": "string",
        "model_id": "string",
        "k": int
      }
    }
  }
}
```

**vector_field** — Field to execute k-NN query against
**query_text** — (string) Query text to be used to produce queries against.
**model_id** — (string) ID of model to do vector to encoding.
**k** — (int) Number of results to return from the k-NN search

For more details, refer to https://github.com/opensearch-project/neural-search/issues/11#issue-1398115115

**Comment by navneet1v** [comment]
@jmazanec15 can you provide details on what will be optional parameters and what are required parameters.
