### ISSUE TITLE
[RFC]: Search Phase Results Processor 

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/neural-search#152]
## Introduction

This issues proposes a new Processor Interface for Search Pipeline which will run in between the Phases of Search. This will allow plugins to transform the results retrieved from one phase before it goes to next phase at the Coordinator Node Level.

## Background[tl;Dr]

This [RFC](https://github.com/opensearch-project/search-processor/issues/80) proposes a new set of APIs to manage Processors to transform Search Request and Responses in OpenSearch. The Search Pipeline will be used to create and define these processors. Example:

### Creating Search Pipeline

```
// Create/update a search pipeline.
PUT /_search/pipeline/mypipeline
{
  "description": "A pipeline to apply custom synonyms, result post-filtering, an ML ranking model",
  "request_processors" : [
    {
      "external_synonyms" : {
        "service_url" : "https://my-synonym-service/"
      }
    },
    {
      "ml_ranker_bracket" : {
        "result_oversampling" : 2, // Request 2 * size results.
        "model_id" : "doc-features-20230109",
        "id" : "ml_ranker_identifier"
      }
    }
  ],
  "response_processors" : [
    {
      "result_blocker" : {
        "service_url" : "https://result-blocklist-service/"
      },
      "ml_ranker_bracket" : {
        // Placed here to indicate that it should run after result_blocker.
        // If not part of response_processors, it will run before result_blocker.
        "id" : "ml_ranker_identifier" 
      }
    }
  ]
}

// Return identifiers for all search pipelines.
GET /_search/pipeline

// Return a single search pipeline definition.
GET /_search/pipeline/mypipeline

// Delete a search pipeline.
DELETE /_search/pipeline/mypipeline

Search API Changes

// Apply a search pipeline to a search request.
POST /my-index/_search?search_pipeline=mypipeline
{
  "query" : {
    "match" : {
      "text_field" : "some search text"
    }
  }
}

// Specify an ad hoc search pipeline as part of a search request.
POST /my-index/_search

{
  "query" : {
    "match" : {
      "text_field" : "some search text"
    }
  },
  "pipeline" : {
    "request_processors" : [
      {
        "external_synonyms" : {
          "service_url" : "https://my-synonym-service/"
        }
      },
      {
        "ml_ranker_bracket" : {
          "result_oversampling" : 2, // Request 2 * size results
          "model_id" : "doc-features-20230109",
          "id" : "ml_ranker_identifier"
        }
      }
    ],
    "response_processors" : [
      {
        "result_blocker" : {
          "service_url" : "https://result-blocklist-service/"
        },
        "ml_ranker_bracket" : {
          // Placed here to indicate that it should run after result_blocker.
          // If not part of response_processors, it will run before result_blocker.
          "id" : "ml_ranker_identifier" 
        }
      }
    ]
  }
}
```

### Index Settings
```
// Set default search pipeline for an existing index.
PUT /my-index/_settings
{
  "index" : {
    "default_search_pipeline" : "my_pipeline"
  }
}

// Remove default search pipeline for an index.
PUT /my-index/_settings
{
  "index" : {
    "default_search_pipeline" : "_none"
  }
}

// Create a new index with a default search pipeline.
PUT my-index
{
  "mappings" : {
    // ...index mappings...
  },
  "settings" : {
    "index" : {
      "default_search_pipeline" : "mypipeline",
      // ... other settings ...
    }
  }
}
```

## Requirement

For [Normalization and Score Combination feature](https://github.com/opensearch-project/neural-search/issues/126), we need a way to do the Normalization of scores received for different sub-queries from different shards at Coordinator node, before we can start combing the scores. This needs to be done after the Query phase is completed and before Fetch Phase is started in a _search api call.

## Solution

The proposed solution is to extend the Search Pipeline Processor Interface to create a new Processor Interface that can run between Phases. We will be onboarding Normalization use-case as the first use case for this processor which will run after Query Phase and Before Fetch Phase of Search Request.

### Proposed Flow Chart
The below flow chart assumes that the processor is running after Query Phase and before Fetch phase for search_type=query_then_fetch which is a default search type. But none of the interface assumes that these are the only 2 phases in the OpenSearch. 

![NormalizationInNeuralSearch-Search Processor Flow (1)](https://user-images.githubusercontent.com/6162415/230508951-a4dc6b78-7852-494e-ab97-9e40c6f5e05f.jpg)

Note: Above diagram can be updated via this [link](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=NormalizationInNeuralSearch#R7Vzbcps6FP0aP9qDxNWPiZO2Z5p20ridtnk5I4NsOAcjF%2BTY6ddXssXNEpgm2NhJkpkEbUAILS1p7S2Jnj6ar9%2FHaOF%2FIh4Oe1Dz1j39qgch1GyD%2FeOWx60FaLa5tcziwBO23DAOfuP0QmFdBh5OShdSQkIaLMpGl0QRdmnJhuKYrMqXTUlYfuoCzbBkGLsolK3fA4%2F6W6tjarn9Aw5mfvpkoIkzc5ReLAyJjzyyKpj0654%2Bigmh26P5eoRDXntpvWzve1dxNitYjCPa5Ib32o%2BhbtzdX65Gztfwe0RnH7W%2BLgr3gMKleGNRWvqYVkFMlpGHeS5aT79c%2BQHF4wVy%2BdkVQ53ZfDoPWQqwQw8l%2FuZanpgGYTgiIYk3Gekews7UZfaExuR%2FXDhjuQ6eTNmZWYy8gL1Q4ZyNkYX5k0VJcUzxurIOQFazrE1iMsc0fmSXrDN4treI5ujYIr3KsTVTbP0CrpYljEi0p1mWd17l7EDU%2Bl8gAIdHRGA6nUJXiYBnTSzTUiMwnXpDyzoMAhZsiAA0DoaA86o5AIcNEdBhCwisx%2FfW3XD88cOvb%2Bg2cvvW%2Fb3b16X6xh7rhUWSxNQnMxKh8Dq3XpYRya%2B5IWQhqv4%2FTOmjGFLQkpIySngd0B%2F89oEpUj8LZ67WIudN4rGQuMVxwF4bx8JWUf%2FsdcgydnHNa6fjGYpnmNZcJ5ojr5NagGMcIho8lEeu1sEyJLaMMYpdn9nu8K8lTqgSzRs0YdqghAAKg1nEjl1Wc7w6L3m7DtjYeyFOzAPP24KNk%2BA3mmzy43W%2BIEFENy9mXvbMKyUKdS1NQSAhIMRDSmO0ikV9bQBNwywxKa2axjiI3G%2F52xQuIdNpgqkEVFaIp2MHZOxY65MB23ZOqeCBZdiYkFnw6%2BbrGRd9g2lIVq7PshkkPLN%2FQUUPWUkUCY3KWtdhucaBou%2FKFFhp%2FD7U4AGkujvVritir1u4iSd%2FFs%2Flt21S6X3Kvudp%2FR1s2N%2BZXXZvsLp7u3BpQKIabVDV8ot93iQh4ZLii9gV8G6secrItEGRfrsqwsSOZ6i1wtD2NNtWKQwHTvSCjmuVibpCxymZmBlbp6J9LlRskVKmTCll3RhHohSZjOjN18mnH8sFevzy7eHrx2uzD9JRN%2BfU3ZLxSPuyxCL7TtRCYxVQxqa68VWyRRvYpj0siwVwQmJB%2BUrOG5%2BqfcZO%2BWS%2BfD45e%2FikS%2BIbPo9Pj8obDseu4Ru7KutG75Rd1stn13APuxxjCFodrbJs4AH4VdfWCigK%2FLRbHyVYwrFLFV%2Bt1Ov0fSUPn67iDUU8%2FMgqHsrB1xPtGI%2FrUVfLkAYd6rE86rpCFph4vcYuY0%2Fep6ac1G5ZXwm1sY9iry83hHPl6LPi9bsctZzuOXo%2BAfvuOaqfA0dlD70ZR%2BWG8Co5amo7s5rdczSd5XvjaAOOGmfBUVnSXhGXGf7xEv68yOO0dEksi9uzdFJA%2FQycNrC1XS9FdEfP9FKM8g2HiwHIU6nVve62v5Wnm15lfwvMk%2Btv9bPxW1rsNxsHdI61YqGulNWhAO2KRCcREcCWp3lYxazh0AKOqWaWZ9r60DuMt%2BF0z6w0IPeqmAWaug2gU00CbIlbn8kLkR9WLVH62gAAB5b1RztR0qPNQYBOJyFAgVc5y%2Fb5CCUPIXcYDu8jNGdkxdzVkaJt8orunzh5IZSsn7dglNQAOPl59crlENlCoyzSEhMXJwmJWZneyfrEJ%2FPJMtmvTXYXgTsuVi8CnzimYWpqkYGRNWlrEbgOdpbxZXq%2BqDKgSmW0sQZZzRvzNaqMxusdjrWAqLaYBca8w7RIle6le%2FdOsbQ49gTW5EE5YHGirMoUBuhOYThNFUa3ml%2FeL7N%2F%2FIJWyN7ochKzoxk%2FSvhegYgGKAzlRRUd8Lf7UdGE5aAWAFb3%2FD2bRbWqrTlPnVnYpNT7fNqZtm863wArfNAjuRK1W32SBYkUQ%2B9Bto7sctXkv9xOSmzc%2Fqg4bG1%2BDjTOGk15erhNpPKatWs%2BHXQMbA5Ro2bnNaqfzRKHFvslXbEjscaF7WwiVLGNLZMewQKHQbSZMcPxQ%2BCehHNwenF9oIFjigvlSlsowZjJxFQlpgbe0ZdQtH4tSXqin2ywuGAXAGOx3t4mzqcZ3eAZjrxMh7LybrMsP4aZC4%2BubDd%2FuwecJ24RZVoi2lhYOUXR01YEFaE2SuqGvuohTtGSJpvfdlqSvbvWRRG7gar941mQp%2FWGJAfUjg7eyRHeTsOM2RS5LcGkK1BqI8CmBEkWkyMfRTMem9YC7j66ZM4kJeZR5F30WDXQHbVSqteIz9%2BWQRCmNKAd4ilVcCwLZ6taRLnNPKFRtAGjuQsjlLttW4Gjfigc5Vhc12Tr3nXfJZsNOyab7A98xitmGKUc4yqPsD8TrpSQx9F6I10V6WzYNenkafauSdd9vFsindUx6eS4KF8LobnZMIfXC%2BzSN6rVUc3qmmqq73HteCUjQmIviBBlSEDtM2FKr4kD8XyU90%2FL78e5BdDMnU9I6aptYyrqHcwDSAv0hlo1atnmvnRpn%2BrjOcdFTQ7kSKhdIYoEXMnrwisLgtZ8Kq8tvFgy%2FxLldqFL%2FkFP%2FfoP).

### Proposed Interface (Recommended)

```
interface SearchPhaseResultsProcessor extends Processor {

    <Result extends SearchPhaseResult> void
            process(final SearchPhaseResults<Result> results, final SearchPhaseContext context);
  /**
    This function is called by Search Pipeline Service before invoking the processor.
  */          
   
   <Result extends SearchPhaseResult> boolean shouldRunProcessor(
        final SearchPhaseResults<Result> results, 
        final SearchPhaseContext context,
        final SearchPhaseNames beforePhase,
        final SearchPhaseNames nextPhase);
}

/**
Currently when we create phases we pass string as the phase name. This enum class
will allow us to define the phase names and use them at different places when required.
*/
// mark internal
public final enum class SearchPhaseNames {
// There are many more, I just added few here.
   QUERY_PHASE("query"), FETCH_PHASE("query"), DFS_QUERY_PAHSE("dfs_query");
   
   @Getter
   String name;
}
```

SearchPhaseNames enum class will provide necessary abstraction and proper naming convention for OpenSearch phase names.

**Pros:**

1. The logic to run a Processor is abstracted with the processor and exposed via a well defined interface.

**Cons:**

1. I don’t see specific cons of this approach. But we have to make SearchPhase class publically accessible which it is not currently. But we can get around this, if we can create SearchPhaseName enums which can be passed. 

### Proposed API
```
// Create/update a search pipeline.
PUT /_search/pipeline/my_pipeline
{
  "description": "A pipeline that adds a Normalization and Combination Transformer",
  "phase_results_processors" : [
    {
      "normalization-processor" : {
        "technique": "min-max", // there can be others techniques. I know this only for now.
      }
    }
  ]
}

// all other APIs remain same for making this pipeline as default pipeline etc.
```

### Alternatives Interface:
The idea here is that the SearchPipeline Service before invoking the execute function of a processor will check whether the condition to run the processor is met or not. The way it checks is it calls the getBeforePhases and getAfterPhases function and checks validates phase which got recently completed is in the the BeforeList and next phase which will be run is in AfterList or not.

```
interface SearchPhaseResultsProcessor extends Procesor {

    <Result extends SearchPhaseResult> void
            process(final SearchPhaseResults<Result> results, final SearchPhaseContext context);
            
   /**
      Returns a list of phases, before which this processor should be run.
   */
   
   List<SearchPhaseNames> getBeforePhases();
    
   /**
      Returns a list of phases, after which this processor should be run.
   */ 
   List<SearchPhaseNames> getAfterPhases();
}

/**
Currently when we create phases we pass string as the phase name. This enum class
will allow us to define the phase names and use them at different places when required.
*/
public final enum class SearchPhaseNames {
// There are many more, I just added few here.
   QUERY_PHASE("query"), FETCH_PHASE("query"), DFS_QUERY_PAHSE("dfs_query");
   
   @Getter
   String name;
}
```

#### Use Search Operation Listener to run code after Query phase is completed

The Search Operation Listeners works at shard level and not the coordinator node level. We need to do the normalization at Coordinator node. Hence rejecting [this](https://github.com/opensearch-project/OpenSearch/blob/c557f2717ad45627cacd88e8243893dd84a56623/server/src/main/java/org/opensearch/search/SearchService.java#L587-L593) solution. Please check [this](https://github.com/opensearch-project/OpenSearch/blob/c557f2717ad45627cacd88e8243893dd84a56623/server/src/main/java/org/opensearch/search/SearchService.java#L1662-L1711), and this code reference. It comes in the code path when Query is getting executed at Shard Level.

#### Create a new Phase between Query and Fetch Phase

The high level idea here is to create a phase which runs in between the Query and Fetch phase which will do the Normalization.
**Pros:**

1. No specific pros that I can think for this approach.

**Cons:**

1. Currently there is not extension points in OpenSearch to create a phase, so we need to build everything from scratch.
2. Problems will arrive in during implementation where code need to identify for which queries this new phase to run, and then we need implement some sophisticated logic to identify that.

#### Create a new Fetch Sub-phase

OpenSearch provides an extension where plugins can add Fetch subphases which will run at the end when all Core Subphases are executed. We can create a Fetch subphase that will do the normalization and score combination. But problem with this, as we have multiple sub-queries we need to change the interfaces to make sure that all the information required for Normalization needs to be passed in. This will result in duplicated information and multiple hacks to pass through the earlier fetch phases.
**Pros:**

1. No new extension points needs to be created as adding new subphases in Fetch phase is already present.

**Cons:**

1. Order of execution of fetch subphases is not consistent. It depends on which plugin got registered first and the fetch sub-phases of that plugin will run first. This will create inconsistency across clusters with different set of plugins. [Code reference](https://github.com/opensearch-project/OpenSearch/blob/515f84bf92ad06f2178d4d5269c38a78a6bf215b/server/src/main/java/org/opensearch/search/SearchModule.java#L1042-L1056).
2. There is a [source subphase](https://github.com/opensearch-project/OpenSearch/blob/515f84bf92ad06f2178d4d5269c38a78a6bf215b/server/src/main/java/org/opensearch/search/SearchModule.java#L1046) which gets the source info for all the docIds, running this before normalization will make OpenSearch get sources for document Ids which we will not be sending in response. Hence waste of computation.

## References
1. Feature Request: https://github.com/opensearch-project/neural-search/issues/139
2. Search Pipeline RFC: https://github.com/opensearch-project/search-processor/issues/80
3. Search Pipeline PR: https://github.com/opensearch-project/OpenSearch/pull/6587

## Feedback Requested:
1. ~We are naming this new Processor interface as SearchPhase Processor, because they run during the phases of Search. Please let us know your thoughts and any better name around this.~ Based on the comments in the PR https://github.com/opensearch-project/OpenSearch/pull/7283, we renamed the interface to SearchPhaseResultsProcessor as it operates on the SearchPhaseResults
2. Any other comment to improve the interface or functionality.

**Comment by jmazanec15** [comment]
@navneet1v This is very interesting!

A couple questions: 

For normalization, can we associate a query type with the processor so that users dont have to manually specify the normalization pipeline anywhere in there query request? How would this look?

Will only one pipeline be allowed to run for each query? Like would it be possible to run one pipeline after query phase and then one pipeline after the fetch phase?

**Comment by jmazanec15** [comment]
In:
```
// Create/update a search pipeline.
PUT /_search/pipeline/mypipeline
{
  "description": "A pipeline to apply custom synonyms, result post-filtering, an ML ranking model",
  "request_processors" : [
    {
      "external_synonyms" : {
        "service_url" : "https://my-synonym-service/"
      }
    },
    {
      "ml_ranker_bracket" : {
        "result_oversampling" : 2, // Request 2 * size results.
        "model_id" : "doc-features-20230109",
        "id" : "ml_ranker_identifier"
      }
    }
  ],
```

Why does ml_ranker_bracket appear in request and result processors?

**Comment by navneet1v** [comment]
> Why does ml_ranker_bracket appear in request and result processors?

This is an example I copied from the Search Pipelines proposal from here: https://github.com/opensearch-project/search-processor/issues/80. I think it's more like an example and not an actual use case.

**Comment by jmazanec15** [comment]
> 1. Given that a normalization processor will evolve and it can have attributes in it, then for every attribute we need to come with default values. Which will result into what should be or should not be the right default value. Avoiding that is a great win for the project.

I think good defaults make feature easier to use - which make the project easier to use - which is a win. The fewer actions the user needs to take to meet their requirements, the better.

> 2. While parsing the search request, we would need to update the search context and logic over there can be complex. Think of complexity in this case, if a customer has attached a pipeline with the query type then we need to parse the pipeline see if the normalization processor is present or not. If its not then update the pipeline which was created by customer. I don't think this is a right behavior. This has potential to add additional latency.

Yes, this might be complex. But I still think we should avoid a user having to maintain a pipeline in order for normalization to work. In other words, normalization should be an out of the box feature - a user shouldnt have to create a pipeline to use it.

Between the following 2 options, I think option 1 is a lot more intuitive user experience.

Option 1:
```
PUT <index-name>/_search
{
    "query": {
        "<new-compound-query-clause>": {
            "queries": [
                { /* neural query */ }, // this is added for an example
                { /* standard text search */ } // If a user want to boost some scores or update 
               // the scores he need to go ahead and do it in this query clause
            ],
            "normalization-technique" : "min-max" // min-max etc.., Optional Object
            "combination" : {
                "algorithm" : "harmonic-mean", // all the values defined in #3 above, interleave, harmonic mean etc
                "parameters" : {
                    // list of all the parameters that can be required for above algo
                    "weights" : [0.4, 0.7] // a floating pointing array which can be used in the algorithm
                }
            }
        }
    }
}
```

Option 2:
```
PUT /_search_processing/pipeline/my_pipeline
{
  "description": "A pipeline that adds a Normalization and Combination Transformer",
  "searchphase_processors" : [
    {
      "normalization-processor" : {
        "technique": "min-max",
      }
    }
  ]
}

PUT <index-name>/_search?pipeline=my_pipeline
{
    "query": {
        "<new-compound-query-clause>": {
            "queries": [
                { /* neural query */ }, // this is added for an example
                { /* standard text search */ } // If a user want to boost some scores or update 
               // the scores he need to go ahead and do it in this query clause
            ]
        }
    }
}
```

Im wondering if we could somehow add parameters in the query that would automatically add this pipeline to the request.

> The ans to this question if you are asking about processor and not pipeline is Yes.

Got it. As a followup, if I have a pipeline where I want a couple processors to run after the query phase and a couple to run after the fetch phase, what would the required ordering be in the pipeline?

**Comment by navneet1v** [comment]
@jmazanec15 
> I think good defaults make feature easier to use - which make the project easier to use - which is a win. The fewer actions the user needs to take to meet their requirements, the better.
> 
> >

This is not always the case and would like understand this from exact requirement standpoint of customer what defaults are needed. Do we need a default pipeline to be added when the new query type is present or not? One reason to not give default pipeline or processor is, the new query clause that we are creating we don't want to make it only usable only for normalization. The output of the query clause provides a way for customers to get separate scores of the queries at coordinator node level and then they can apply any transformation on top of that.

On on the option of using 1 & 2, customers already have a way in which they can specify the pipeline in the _search request, by making a small change in Option 1. 

```
POST /my-index/_search

{
  "query": {
        "<new-compound-query-clause>": {
            "queries": [
                { /* neural query */ }, // this is added for an example
                { /* standard text search */ } // If a user want to boost some scores or update 
               // the scores he need to go ahead and do it in this query clause
            ]
  },
  "pipeline" : {
    "searchphase_processors" : [
      {
        "normalization-processor" : {
          "technique": "min-max",
          "combination" : {
                "algorithm" : "harmonic-mean", // all the values defined in #3 above, interleave, harmonic mean etc
                "parameters" : {
                              // list of all the parameters that can be required for above algo
                              "weights" : [0.4, 0.7] // a floating pointing array which can be used in the algorithm
                }
            }
        }
      }
    ]
  }
}



```

**Comment by navneet1v** [comment]
> Got it. As a followup, if I have a pipeline where I want a couple processors to run after the query phase and a couple to run after the fetch phase, what would the required ordering be in the pipeline?

```
PUT /_search_processing/pipeline/my_pipeline
{
  "description": "A pipeline that adds a Normalization and Combination Transformer",
  "searchphase_processors" : [
    {
      "processor1" : { // runs after fetch phase
      }
    },
    {
      "processor2" : { // runs after query phase and before fetch phase
      }
    },
    {
      "processor3" : { // runs after dfs phase and before query phase
      }
    }

  ]
}
```

Consider a pipeline like this, in this case the SearchPipeline Service after every phase will invoke the `shouldRunProcessor` function of each processor to see if it can run that processor. These function are invoked in the order of how processors are defined in the pipeline in array : `searchphase_processors`

processor1 will only run once the fetch phase is completed. This is just an example, customer might want to use search response processors instead of this. But just for example sake.
processor2: will run when the query phase is completed and next phase is fetch phase only.
processor3: will run once the dfs phase is done and query phase is the next phase.

I hope this ans the question.

**Comment by navneet1v** [comment]
Updated the description. Based on the comments on the PR, the processor interface is renamed to SearchPhaseResultsProcessor. The idea is this processor operators on SearchPhaseResults, hence SearchPhaseResultsProcessor.
