### ISSUE TITLE
 [FEATURE] New Query for Normalization and Score Combination Query

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/neural-search#175]
## Description
For Normalization and Score Combination feature, we need a new Query clause that holds multiple sub-queries of different types. The query will be executed in a _search API call.

## Solution
Solution that is proposed here is to create new implementation of a [QueryBuilder](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/query/QueryBuilder.java) and [Query](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/search/Query.java). Those classes mainly will be responsible for parsing new query clause and creating instances of corresponding sub-query types.

Because special logic is required for scores we also need a new implementation of [Scorer](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/search/Scorer.java). New scorer will accumulate scores from multiple sub-queries.

## Tasks
- [X] Create RFC for new Query Clause: https://github.com/opensearch-project/neural-search/issues/174
- [x] Implementation of a Query clause
- [x] Testing

## Reference Links
1. https://github.com/opensearch-project/neural-search/issues/126
2. https://github.com/opensearch-project/neural-search/issues/174

**Comment by navneet1v** [comment]
Resolving this github issue as the changes for RC of 2.10 is finalized and merged. Please create a github issue if there are any further questions.
