### ISSUE TITLE
Create text_embedding type processor for ingest pipeline processing

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/neural-search#19]
# Problem statement
Before querying with neural search, all the documents should be ingested in the form of embedded vectors. Leaving the embedding process to the user offline will raise the bar of use. Thus we propose to implement the ingestion pipeline of document embedding. It consists of two parts:
1. User will have the flexibility to decide which field should be embedded and which need not.
2. A `model_id` will be dedicated for each processor and this kind of mapping can be retrieved by the querying phase.
# Solution
A new processor type needs to be created with name: `text_embedding`, this processor has two parameters: `model_id` and `field_map`. Different models can produce different embedding results, user can specify a `model_id` which is already uploaded and loaded, `field_map` is the configuration user can specify which fields should apply text embedding in the ingestion pipeline. An example below:

```
PUT _ingest/pipeline/text-embedding-pipeline
{
    "description": "Text embedding pipeline for several fields",
    "processors": [
        {
            "text_embedding": {
                "model_id": "WYjkv4MBHcWxVq8Jtc8U",
                "field_map": {
                    "title": "title_knn",
                    "body_list": "body_list_knn",
                    "favorites": {
                        "game": "game_knn",
                        "movie": "movie_knn"
                    }
                }
            }
        }
    ]
}
```

**Comment by navneet1v** [comment]
@zane-neo can we close this issue?
