### ISSUE TITLE
Add ability to run integration tests on secure OpenSearch cluster

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/neural-search#201]
Need feature of running integ tests on secure OpenSearch cluster or similar environment with enabled security plugin.

k-NN plugin has [something similar](https://github.com/opensearch-project/k-NN/blob/main/.github/workflows/test_security.yml) as part of the CI, but test runs are flaky. That approach is based on docker setup that depends on distribution builds and also hard to troubleshoot in case there are errors.  

Alternative approach is discussed [here](https://github.com/opensearch-project/k-NN/issues/901), we can install security plugin and run tests locally without spinning up a docker with min distribution.

**Comment by vibrantvarun** [comment]
Code has been shipped.
