### ISSUE TITLE
Add backwards compatibility tests for automation

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/neural-search#202]
Add backwards compatibility tests for the plugin to automate end-to-end upgrade paths for faster releases.
Developer documentation for implementing bwc tests and hooking them to CI: https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#backwards-compatibility-testing

This would include the BWC tests on both plugin level and distribution bundle level.

**Comment by navneet1v** [comment]
@vamshin can you assign an owner for this task?

**Comment by zelinh** [comment]
Hey @vibrantvarun, It seems like you have added the BWC tests for neural search on the plugin level with only necessary dependency plugins that neural search needs. 

We also have a framework for BWC tests on distribution level as well which will set up the test cluster with the bundle distribution including all plugins engineering effectiveness team builds. Are you plan to add that part as well? 

I believe it will be beneficial during the release cycle since we will be testing the exact distribution that we would ship to the customers.

It's a straightforward step based on what you already worked on the BWC tests. More onboarding info can be found [here](https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#bwc-tests-on-distribution-bundle-level). 

cc: @vamshin @bbarani

**Comment by vibrantvarun** [comment]
BWC tests at plugin level and distribution level are added now. Therefore closing the issue.
