### ISSUE TITLE
Tune the error message if model fails to generate embedding

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/neural-search#229]
When model fails to generate embedding, neural search will return null pointer exception. How about we check the result first and throw a more readable error message like "No embedding generated from model"?
```
{
   "type":"null_pointer_exception",
   "reason":"Cannot read the array length because \"array\" is null"
}
```

**Comment by martin-gaievski** [comment]
Looks like this is done in [InferenceProcessor](https://github.com/opensearch-project/neural-search/blob/main/src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java#L383-L388) as part of PR https://github.com/opensearch-project/neural-search/pull/333
