### ISSUE TITLE
[FEATURE] Run integration tests as part of the OpenSearch distribution

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/neural-search#24]
**Is your feature request related to a problem?**
Following a problem in another plugin (https://github.com/opensearch-project/opensearch-build/issues/2043), and coming from https://github.com/opensearch-project/opensearch-build/issues/58, there's no automated testing that this plugin runs as part of the OpenSearch distribution.

**What solution would you like?**
Run integration tests as part of the distribution.

**Comment by navneet1v** [comment]
Currently the CI is not passing. We have the PR which are fixing that. Once the PR is merged I will start raising the PR for running the integration tests as part of OS distribution

**Comment by jmazanec15** [comment]
This should be complete.
