### ISSUE TITLE
[BUG] Rebase Main Branch w/ Refactors from upstream core

### ISSUE THREAD

**Issue by nknize** [opensearch-project/neural-search#240]
### What is the bug?
Build fails with some latest dependency updates from core. This was caught by the [compatibility checker](https://github.com/opensearch-project/OpenSearch/actions/runs/5742101583/job/15563536027?pr=9073#step:3:2097) on https://github.com/opensearch-project/OpenSearch/pull/9073.

### How can one reproduce the bug?
Build with latest core Snapshot.

### What is the expected behavior?
Build passes w/o any updateShas failures

### Do you have any screenshots?
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':updateShas'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Conflict(s) found for the following module(s):
       - org.apache.logging.log4j:log4j-api between versions 2.20.0 and 2.17.1
       - org.apache.logging.log4j:log4j-core between versions 2.20.0 and 2.17.1
     Run with:
         --scan or
         :dependencyInsight --configuration runtimeClasspath --dependency org.apache.logging.log4j:log4j-api
     to get more insight on how to solve the conflict.
```

### Do you have any additional context?
[#5910](https://github.com/opensearch-project/OpenSearch/issues/5910)

**Comment by gaiksaya** [comment]
Issue with console logs. Neural plugin is good as per the final result:


Incompatible components: [https://github.com/opensearch-project/index-management.git, https://github.com/opensearch-project/anomaly-detection.git, https://github.com/opensearch-project/asynchronous-search.git, https://github.com/opensearch-project/geospatial.git, https://github.com/opensearch-project/performance-analyzer.git, https://github.com/opensearch-project/security-analytics.git]
