### ISSUE TITLE
Update Main branch of Plugin to point to 3.0.0

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/neural-search#30]
### Description
Update Main branch of Plugin to point to 3.0.0 for OpenSearch and all the dependent plugins.

**Comment by jmazanec15** [comment]
Need to wait for this until ml-commons imports model code to main.

**Comment by navneet1v** [comment]
Closing the issue. It got implemented in this PR: https://github.com/opensearch-project/neural-search/pull/87
