### ISSUE TITLE
[FEATURE] Support multi-modal semantic search 

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/neural-search#318]
### Is your feature request related to a problem?
This feature aims to enhance semantic search use cases by enabling Multimodal support in Neural Search plugin.  Multimodal improves the relevancy of the results by combining text and other forms of inputs like image, audio, video etc. 
As of today OpenSearch supports Semantic search use cases purely based on text based embedding models. While this works for majority of usecases, it does not scale well for applications that need to embed other forms of input. For example, consider a query “Give me bright colored blue shoes”. This can get more relevant results if image properties such as color, intensity is captured along with text. Multimodal solves this problem

### What solution would you like?
- We can make use of [Binary field](http://a%20binary%20field%20type%20contains%20a%20binary%20value%20in%20base64%20encoding%20that%20is%20not%20searchable./) in OpenSearch to accept other forms of inputs like images, audio, video.
- Enhance existing text embedding processor/create new processor to accept the binary fields and pass to ml-commons to get relevant embedding
- Enhance neural query clause to accept binary along with string to perform semantic search

**Comment by martin-gaievski** [comment]
@vamshin for 2.11 we can do only limited support due to tight deadline. I see that is added to the roadmap, do you want to keep it as is and we create a new feature request for a extended solution, or we can remove 2.11 label and keep using this issue.

**Comment by vamshin** [comment]
@martin-gaievski I think we should create new one for tracking extended solutions and tag this issue as a parent issue. This way community knows this feature is already shipped.
