### ISSUE TITLE
[FEATURE] Pulling fields content for neural search from user provided URL

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/neural-search#475]
### Is your feature request related to a problem?
Today the content for the text and images for mutimodal semantic search is provided directly with the request in form of base64 encoded string. This requires additional pre-processing of data and not be optimal is some scenarios when for instance data is already available in some other system. Another problem is storage space, in OpenSearch this binary content will be stored as part of the index.  

### What solution would you like?
Allow URLs for fields, something around these lines:
```
  "query": {
        "neural": {
              "vector_embeddings": {
                  "query": {
                        "image":  {
                            "value": "http://myserver/image1.jpg"
                            "type": "url"
                        },
```

### What alternatives have you considered?
Alternative is available now, user needs to download content from the URL and do base64 encoding

### Do you have any additional context?
There can be concerns around security as system will be pulling from remote URLs. Most probably the syntax of existing requests will change to support url type

**Comment by Sanjana679** [comment]
I wanted to clarify, this method with the URL would only be for search and not for ingesting documents?

**Comment by Sanjana679** [comment]
I've been trying to tackle this issue as well, but I'm stuck. Opening a socket connection within NeuralQueryBuilder is forbidden so I'm not sure what I can do instead.

**Comment by martin-gaievski** [comment]
This idea may not be ideal for managed systems, mainly because URL is provided by user and that may be not secure and/or can affect system stability. At some degree the overhead with storage can be solved by not storing field source in the index.
