### ISSUE TITLE
[FEATURE] post_filter to be supported with Hybrid Search

### ISSUE THREAD

**Issue by ankitas3** [opensearch-project/neural-search#508]
**Is your feature request related to a problem?**
Currently post_filter sent in query is not supported with Hybrid Query. The results are not reflected as per the filter applied.

**What solution would you like?**
post_filter should be supported and the results should be filtered from the hybrid query results.

**Comment by ulan-yisaev** [comment]
Please implement this feature, it is very needed!

**Comment by vamshin** [comment]
@ulan-yisaev we are actively working on this and hoping to make it to 2.13 release

**Comment by vibrantvarun** [comment]
PR has been merged and we can close the issue now
