### ISSUE TITLE
[Feature] Add efficient k-NN filtering support to Neural query

### ISSUE THREAD

**Issue by SeyedAlirezaFatemi** [opensearch-project/neural-search#523]
### Is your feature request related to a problem?
Currently, there is no way to use efficient k-NN filtering with a Neural query ([documentation](https://opensearch.org/docs/latest/query-dsl/specialized/neural/))

### What solution would you like?
Adding a filter field to the neural query which is pretty similar to the syntax of efficient k-NN filtering:
```
"neural": {
  "<vector_field>": {
    "query_text": "<query_text>",
    "query_image": "<image_binary>",
    "model_id": "<model_id>",
    "k": 100,

    "filter": {
      ...
    }

  }
}

**Comment by navneet1v** [comment]
@SeyedAlirezaFatemi the feature is already supported with neural query clause and works exactly you have defined in the description.

The documentation is not updated to say that it is supported,

cc: @jmazanec15 @vamshin

**Comment by SeyedAlirezaFatemi** [comment]
I think the Java Client for OpenSearch also doesn't support it.

**Comment by jmazanec15** [comment]
For filtering support, we do mention it here: https://opensearch.org/docs/latest/search-plugins/semantic-search/#step-4-search-the-index-using-neural-search. That being said, its not easy to find. We should have a section on the query itself and the parameters of the query.

**Comment by navneet1v** [comment]
> I think the Java Client for OpenSearch also doesn't support it.

@SeyedAlirezaFatemi for which java client? high level java rest client or opensearch-java(low level client)?

**Comment by SeyedAlirezaFatemi** [comment]
@navneet1v opensearch-java. [NeuralQuery](https://github.com/opensearch-project/opensearch-java/blob/main/java-client/src/main/java/org/opensearch/client/opensearch/_types/query_dsl/NeuralQuery.java)

**Comment by navneet1v** [comment]
@SeyedAlirezaFatemi thanks for providing the details. I need to move this issue to opensearch-java repo, as the changes need to happen there. 

cc: @VachaShah, @vamshin , @dblock , @jmazanec15

**Comment by rahulbhatia2702** [comment]
@navneet1v is prefiltering also available for neural sparse search ?

**Comment by navneet1v** [comment]
> @navneet1v is prefiltering also available for neural sparse search ?

@zane-neo can you please reply on this.

**Comment by heemin32** [comment]
Closing the issue. Please reopen the issue in java client repo.
For sparse vector search, it works in a manner similar to text search. Therefore, the concept of pre-filtering does not apply.
