### ISSUE TITLE
Add validation for reranker processor parameters

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/neural-search#555]
For the [reranker processor](https://github.com/opensearch-project/neural-search/issues/248), there are no checks of number of context fields user can define for the processor when:

- defining processor as part of the search pipeline
- using `query_text_path` as part of search request

This brings risks of system instability in case very long string is passed in any of those two places.

I suggest we use some limit on number of fields for `document_fields`, let's start from 50 but that number is discussible. For the `query_text_path` we can limit the max level of nested field to not exceed one that set by `index.mapping.depth.limit` [setting](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/MapperService.java#L149).

**Comment by martin-gaievski** [comment]
@HenryL27 please check this request

**Comment by HenryL27** [comment]
ack

**Comment by HenryL27** [comment]
any other instabilities?

**Comment by martin-gaievski** [comment]
> any other instabilities?

not as of now, but let's keep this issue open, I may add more stuff in coming days. this is based on a feedback I'm getting from security reviews
