### ISSUE TITLE
[BUG] Reranking makes relevancy worse, somehow

### ISSUE THREAD

**Issue by HenryL27** [opensearch-project/neural-search#588]
### What is the bug?
Doing some testing on a cluster, and relevancy seems to decrease...
Anecdotally, the reranking feature has made search quality better, but I've only ever run it on single node clusters. Now, relevency gets worse, e.g. (ndcg@10)
| dataset | pure neural | minilm reranker | bge reranker | quantized bge reranker |
| ---- | ------ | ----- | ------ | ------ |
| fiqa | 0.3859 | 0.3098 | 0.2574 | 0.0783 |

### How can one reproduce the bug?
cluster with 3 r5.8xlarge

### What is the expected behavior?
ndcg@10 should get better

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by HenryL27** [comment]
Not sure. deploying the model on only one node doesn't do it tho

**Comment by navneet1v** [comment]
@HenryL27 is the bug resolved?

**Comment by HenryL27** [comment]
ran on a single node cluster and I have similar results, so I think it's just a model problem. I think we can close this.
