### ISSUE TITLE
[BUG] Status code 500 for hybrid queries with preference=_local flag

### ISSUE THREAD

**Issue by ksingh17i** [opensearch-project/neural-search#606]
### What is the bug?
We are getting status 500 on open search dashboard when running hybrid queries with **preference=_local** and **request_cache=true** flags. The initial investigation shows the error occurs if the index has 1 shard. 

### How can one reproduce the bug?
1. Create one index with only one shard
2. Populate the data
3. Run hybrid query with the search pipeline and with **preference=_local** and **request_cache=true** flags

### What is the expected behavior?
The query should return the matching result with status code 200

### What is your host/environment?
AWS Managed OpenSearch 2.11

### Do you have any screenshots?
Please find the screenshot attached

### Do you have any additional context?
<img width="1512" alt="image001" src="https://github.com/opensearch-project/neural-search/assets/154556101/aabfaa9b-5bc9-4fee-bb39-74798c4f607e">

**Comment by ksingh17i** [comment]
adding @navneet1v in loop, Navneet do we have any ETA for this issue?

**Comment by vamshin** [comment]
@ksingh17i We are evaluating the effort. Will update the ETA soon.

**Comment by ksingh17i** [comment]
Hi @vamshin, could you please help prioritizing this and let us know by when can we expect a fix for this.

**Comment by navneet1v** [comment]
@martin-gaievski lets close this issue as the feature is merged.
