### ISSUE TITLE
[FEATURE] support default model id in `neural_sparse` query

### ISSUE THREAD

**Issue by zhichao-aws** [opensearch-project/neural-search#610]
### Is your feature request related to a problem?
Currently, users need to provide the `model_id` in `neural_sparse` query. This is not convinient and requires more effort to maintain the model id. We should support default model id in `neural_sparse` query just like neural query and hybrid query.

ref: #70 #337

**Comment by zhichao-aws** [comment]
Please assign this ticket to me. It is target the 2.13 release.

**Comment by vibrantvarun** [comment]
https://github.com/opensearch-project/neural-search/pull/541

@zhichao-aws sharing this PR above for reference.
