### ISSUE TITLE
[META] Chunking and querying of long passages for vector search

### ISSUE THREAD

**Issue by samuel-oci** [opensearch-project/neural-search#612]
### Is your feature request related to a problem?
This is meta issue that orchestrate all tasks related to chunking and search of long passages and include both ingest, storage and query paths.

**RFC ingest path:**
https://github.com/opensearch-project/neural-search/issues/548

**RFC query path:**
TBD

**RFC storage path:**
TBD

**Issues:**
https://github.com/opensearch-project/k-NN/issues/1065
https://github.com/opensearch-project/neural-search/issues/482

**Comment by yuye-aws** [comment]
Thanks @samuel-oci ! This is the draft PR to implement fixed token length algorithm and ingest processor: https://github.com/opensearch-project/neural-search/pull/607.

**Comment by martin-gaievski** [comment]
should we link https://github.com/opensearch-project/neural-search/issues/794 and https://github.com/opensearch-project/neural-search/issues/751 to this meta issue?

**Comment by navneet1v** [comment]
@samuel-oci can we close this issue. As the chunking processor is launched.

**Comment by yuye-aws** [comment]
Closing this issue as text chunking processor has been released.
