### ISSUE TITLE
[Infrastructure] BWC tests for Chunking Processor 

### ISSUE THREAD

**Issue by vibrantvarun** [opensearch-project/neural-search#647]
BWC tests for chunking processor wrt [607](https://github.com/opensearch-project/neural-search/pull/607)

**Comment by vibrantvarun** [comment]
@yuye-aws Can you add the bwc tests for the feature.

**Comment by yuye-aws** [comment]
This feature implements a new processor for text chunking, which does not break any existing functionalities. I do not think there is any potential risk of breaking the backward compatibility. You can also verify that with my code. Can we simply close this issue?

**Comment by yuye-aws** [comment]
Feel free to raise any concerns regarding the necessity of BWC test.

**Comment by vibrantvarun** [comment]
@yuye-aws We need BWC tests for future releases. Like when 2.14 will be released then we need to run bwc test for the same functionality.

**Comment by yuye-aws** [comment]
Hi @vibrantvarun , can I follow your [PR](https://github.com/opensearch-project/neural-search/pull/533) in this issue? Is BWC test a hard requirement for 2.14 release?

**Comment by navneet1v** [comment]
> Hi @vibrantvarun , can I follow your [PR](https://github.com/opensearch-project/neural-search/pull/533) in this issue? Is BWC test a hard requirement for 2.14 release?

I would say right now as a best practice we should add the BWC test. This will help in future to catch bugs if we are making changes in these processors or if any breaking change comes from Opensearch core. 

I am coming up with the more detailed developer guide for adding new features in neural search plugin and I will include this as a point there. We can discuss whether BWC should be a hard requirement there and lets other maintainers share their thoughts.

**Comment by yuye-aws** [comment]
Sure. I will implement the BWC tests.

**Comment by yuye-aws** [comment]
Hi @navneet1v and @vibrantvarun ! This PR implements the BWC test for text chunking processor. Can you help review?

**Comment by vibrantvarun** [comment]
Reviewed and added the comments.
