### ISSUE TITLE
[BUG] BWC are failing for main -> 2.14.0-SNAPSHOT

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/neural-search#688]
### What is the bug?
Rolling upgrade BWC tests are failing for `main` branch:

```
./gradlew :qa:rolling-upgrade:testRollingUpgrade -D'tests.bwc.version=2.14.0-SNAPSHOT'

> Task :qa:rolling-upgrade:testAgainstOneThirdUpgradedCluster FAILED

FAILURE: Build failed with an exception.
```

### How can one reproduce the bug?
Get `main` of this repo, run `./gradlew :qa:rolling-upgrade:testRollingUpgrade -D'tests.bwc.version=2.14.0-SNAPSHOT'` 

### What is the expected behavior?
Tests are passing

### What is your host/environment?
Issue happens only on Linux, for Win platform everything works. 
Following is the link to example of failed run for one of recent PRs, same error/behavior observed for `main` as well 
https://github.com/opensearch-project/neural-search/actions/runs/8649948821/job/23718643879?pr=683

**Comment by vibrantvarun** [comment]
@martin-gaievski can you add the error logs?

**Comment by martin-gaievski** [comment]
It's in related issue https://github.com/opensearch-project/neural-search/pull/683#issuecomment-2048608920
