### ISSUE TITLE
[BUG] Default model id not working for nested field

### ISSUE THREAD

**Issue by yuye-aws** [opensearch-project/neural-search#738]
### What is the bug?
Here is the discussion from the forum: https://forum.opensearch.org/t/set-up-default-model-id-for-neural-query-enricher-with-nested-knn-field/19217

### How can one reproduce the bug?
Follow steps in: https://forum.opensearch.org/t/set-up-default-model-id-for-neural-query-enricher-with-nested-knn-field/19217

### What is the expected behavior?
We need to support default model id for nested field.

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by vibrantvarun** [comment]
duplicate issue with https://github.com/opensearch-project/neural-search/issues/813. As 813 is fixed, we can mark this as closed.
