### ISSUE TITLE
[ Bug ] Neural Search Leads to "modelId is marked non-null but is null" when Targeting Multiple Indices

### ISSUE THREAD

**Issue by imbarazz** [opensearch-project/neural-search#759]
Note: this error was observed on OpenSearch 2.11 running on AWS cloud.

Performing a neural search against an alias, or performing a multi-search with multiple indices in a single header leads to the following error: 

`"null_pointer_exception: modelId is marked non-null but is null".`

This is problematic when searching across different indices, each with their own embedding model.

#### Search Pipeline for Embedder Model 1 ####
`PUT /_search/pipeline/embed_pipeline_1`
```json
{
  "request_processors": [
    {
      "neural_query_enricher": {
        "neural_field_default_id": {
          "common_vector_field": "embed_model_id_1"
        }
      }
    }
  ]
}
```
#### Search Pipeline for Embedder Model 2 ####
`PUT /_search/pipeline/embed_pipeline_2`
```json
{
  "request_processors": [
    {
      "neural_query_enricher": {
        "neural_field_default_id": {
          "common_vector_field": "embed_model_id_2"
        }
      }
    }
  ]
}
```
#### Update Index 1 with Pipeline 1 ####
`PUT /index1/_settings`
```json
{
  "index.search.default_pipeline" : "embed_pipeline_1"
}
```
#### Update Index 2 with Pipeline 2 ####
`PUT /index2/_settings`
```json
{
  "index.search.default_pipeline" : "embed_pipeline_2"
}
```
#### Perform Multi-Search ####
`GET /_msearch`
```json
{
  "index": [
    "index1",
    "index2"
  ]
}
{
  "query": {
    "neural": {
      "common_vector_field": {
        "query_text": "How do I perform a neural multi-search when dealing with multiple indices?",
        "k": 5
      }
    }
  },
  "from": 0,
  "size": 5
}
```

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by imbarazz** [comment]
Playing around with this further, I've come to the realization that the issue here is that the _index.search.default_pipeline_ assigned to an index does not take effect when targeting multiple indices via alias or multi-search. To get this to work, one must explicitly pass the search-pipeline via url parameter like so:

`/my_alias/_search?search_pipeline=my_search_pipeline`

**Comment by vibrantvarun** [comment]
@martin-gaievski I don't think it as a bug. thoughts?

**Comment by martin-gaievski** [comment]
if I understood this correctly the `index.search.default_pipeline` does support only single index search, correct? If that's the case then enricher processor will work the same way, this is expected. I have doubt about the error message, we can give some meaningful error, something that is actionable from user perspective.

**Comment by imbarazz** [comment]
> if I understood this correctly the `index.search.default_pipeline` does support only single index search, correct? If that's the case then enricher processor will work the same way, this is expected.

Thanks for the reply.

Currently, an index's configured `neural_enricher` is being completely ignored during a neural search against an alias. Is this expected behaviour? This seems strange  to me.

**Comment by martin-gaievski** [comment]
It's not an expected behavior, more like a gap, team didn't check this scenario.

Do these steps summarize the issue correctly:
- create index `index_A` with default model assigned via `index.search.default_pipeline` index setting, e.g. `model_id_1`
- create alias `alias_A` with some filter and refer to `index_A`
- run hybrid query, set `alias_A` as an index for the query. use neural query, do not put any model id

expected result is: hybrid query executed, for neural search sub-query model `model_id_1` got picked up from the index setting for `index_A`

**Comment by navneet1v** [comment]
@minalsha, @martin-gaievski , @vibrantvarun

**Comment by Romasato** [comment]
Ran into this very same issue just today - was hoping to get away from needing to pass in ML Model ID in Search query...

Then, as a workaround, I was planning to use the `search_pipeline=` query string param with search request, but I could not find a way to pass this extra parameter via .NET higher nor lower level client lib..

Any suggestions?

**Comment by aalbahem** [comment]
I encountered the same bug today. It was unexpected, and it would be beneficial to resolve it or prioritize it. Additionally, highlighting this issue in the documentation for now would be helpful.

**Comment by vibrantvarun** [comment]
Search pipelines are not supported with `msearch` until now. [PR](https://github.com/opensearch-project/OpenSearch/pull/15923) of the support has already been raised and merged by @owaiskazi19  in OpenSearch. In the next OpenSearch release, the support for search pipelines will be enabled with `msearch`.

**Comment by vibrantvarun** [comment]
From OpenSearch 2.18, You can explicitly pass search pipeline in _msearch api.
```
{"index":["my-nlp-index","my-nlp-index1"]}
{"query" : {"hybrid" : {"queries":[{"neural":"common_vector_field": {"query_text": "How do I perform a neural multi-search when dealing with multiple indices?","k": 5}}]}}, "from" : 0, "size" : 10,"search_pipeline":"nlp-search-pipeline"}
```

**Comment by vibrantvarun** [comment]
For multiple index you can explicitly define the search pipeline now. Therefore after enabling the support of search pipeline this bug is resolved.
