### ISSUE TITLE
[INFRASTRUCTURE] BWC tests for batch ingestion in TextEmbeddingProcessor and SparseEncodingProcessor

### ISSUE THREAD

**Issue by vibrantvarun** [opensearch-project/neural-search#763]
Add BWC tests for batch Ingestion for TextEmbeddingProcessor and SparseEncodingProcessor.

**Comment by zhichao-aws** [comment]
@chishui Please follow up this issue. Not sure whether it's a bug for GH, I can not assign this issue to you

**Comment by chishui** [comment]
PR: https://github.com/opensearch-project/neural-search/pull/769

**Comment by vibrantvarun** [comment]
PR is merged therefore we can close the issue.
