### ISSUE TITLE
[FEATURE] Set neural-search plugin 3.0.0 baseline JDK version to JDK-21

### ISSUE THREAD

**Issue by reta** [opensearch-project/neural-search#775]
### Is your feature request related to a problem? Please describe

Set `neural-search` plugin 3.0.0 baseline JDK version to JDK-21

### Describe the solution you'd like

See please https://github.com/opensearch-project/OpenSearch/issues/10745

### Related component

Build

### Describe alternatives you've considered

N/A

### Additional context

See please https://github.com/opensearch-project/OpenSearch/issues/14011

**Comment by dblock** [comment]
[Catch All Triage - Attendees [1](https://github.com/dblock/), [2](https://github.com/krisfreedain), [3](https://github.com/andrross), [4](https://github.com/gkamat), [5](https://github.com/getsaurabh02)]

**Comment by martin-gaievski** [comment]
following PRs related to adding JDK21, they were done before/separately from this campaign:

https://github.com/opensearch-project/neural-search/pull/565
https://github.com/opensearch-project/neural-search/pull/801
https://github.com/opensearch-project/neural-search/pull/837
https://github.com/opensearch-project/neural-search/pull/801

**Comment by martin-gaievski** [comment]
@reta is there anything left for neural search plugin in scope of this campaign? We have done multiple small PRs that added jdk21 to different plugin areas, list is here https://github.com/opensearch-project/neural-search/issues/775#issuecomment-2239551341.

**Comment by reta** [comment]
> @reta is there anything left for neural search plugin in scope of this campaign? We have done multiple small PRs that added jdk21 to different plugin areas, list is here [#775 (comment)](https://github.com/opensearch-project/neural-search/issues/775#issuecomment-2239551341).

Yes, we need to update baseline here https://github.com/opensearch-project/neural-search/blob/main/build.gradle#L158

```
allprojects {
    ...
    targetCompatibility = JavaVersion.VERSION_21
    sourceCompatibility = JavaVersion.VERSION_21
    ...

```
