### ISSUE TITLE
[BUG] Hybrid Search results are missing when concurrent search is enabled

### ISSUE THREAD

**Issue by vibrantvarun** [opensearch-project/neural-search#799]
### What is the bug?
Hybrid search results are missing when concurrent search is enabled in single shard and multiple shards scenario.  
**For example:**
For **single** shard I ingested 6 documents and did a matchAll query under the hybrid clause then I am expecting **6** results should be there but I am getting just **5** results.

For **multiple** shard I did the same by ingesting 100 documents and I am expecting **100** results but getting **95**.

### How can one reproduce the bug?
1) Just ingest the documents for single shard by following URL  http://localhost:9200/my-nlp-index/_doc/1?refresh=true and make sure update docId when ingesting new documents.
2) Enable the concurrent search in index settings
3) For multiple shard use code to ingest 100 documents in a same way
4) Do a match all query with maximum results size, you will find the results are missing.

### What is the expected behavior?
Results should not be missing and the right of results should be returned.

### Do you have any additional context?
When concurrent search is disabled everything is working fine.

**Comment by vibrantvarun** [comment]
@martin-gaievski assigning this to you

**Comment by vibrantvarun** [comment]
@martin-gaievski Can we close the bug?

**Comment by martin-gaievski** [comment]
yup
