### ISSUE TITLE
Neural Search Plugin CI's are failing

### ISSUE THREAD

**Issue by vibrantvarun** [opensearch-project/neural-search#816]
Currently, the Neural Search Plugin CI's are failing and serveral BWC tests are also failing.

**Comment by vibrantvarun** [comment]
The issue could be due to below 2 PR's
https://github.com/opensearch-project/neural-search/pull/814

https://github.com/opensearch-project/k-NN/pull/1783

**Comment by vibrantvarun** [comment]
@shatejas  Can you look into this.

**Comment by navneet1v** [comment]
@vibrantvarun #814 is not even merged, how that can be cause of this failure?

**Comment by navneet1v** [comment]
The fixes are merged. Will see if the issue was due ti flaky test or interface change from knn plugin.

**Comment by navneet1v** [comment]
Started re-runs of the gh actions

**Comment by vibrantvarun** [comment]
@navneet1v did the tests pass after the rerun?
