### ISSUE TITLE
[PROPOSAL] Block track_scores=true in hybrid search

### ISSUE THREAD

**Issue by vibrantvarun** [opensearch-project/neural-search#849]
### What are you proposing?
To maintain the consistent customer experience across hybrid search with and without sorting, we should block track_scores=true in standard hybrid search. Currently, track_scores=true is blocked in when sorting is applied. To add more context, scores are by default calculated regardless of track_scores value.

### What problems are you trying to solve?
_Summarize the core use cases and user problems and needs you are trying to solve. Describe the most important user needs, pain points and jobs as expressed by the user asks above. Template: When \<a situation arises> , a \<type of user> wants to \<do something>, so they can \<expected outcome>. (Example: When **searching by postal code**, **a buyer** wants to **be required to enter a valid code** so they **don’t waste time searching for a clearly invalid postal code.**)_

Consistent customer experience

### What is the developer experience going to be?
_Does this have a REST API? If so, please describe the API and any impact it may have to existing APIs. In a brief summary (not a spec), highlight what new REST APIs or changes to REST APIs are planned. as well as any other API, CLI or Configuration changes that are planned as part of this feature._

Just add a check for track_scores=true in hybrid collector manager where we create the collector manager object and throw illegal argument exception.

#### Are there any security considerations? 
_Describe if the feature has any security considerations or impact. What is the security model of the new APIs? Features should be integrated into the OpenSearch security suite and so if they are not, we should highlight the reasons here._
No
#### Are there any breaking changes to the API
_If this feature will require breaking changes to any APIs, ouline what those are and why they are needed. What is the path to minimizing impact? (example, add new API and deprecate the old one)_
No

### What is the user experience going to be?
_Describe the feature requirements and or user stories. You may include low-fidelity sketches, wireframes, APIs stubs, or other examples of how a user would use the feature via CLI, OpenSearch Dashboards, REST API, etc. Using a bulleted list or simple diagrams to outline features is okay. If this is net new functionality, call this out as well._

An error message would be thrown when track_scores=true is passed in standard hybrid search request.

#### Are there breaking changes to the User Experience?
_Will this change the existing user experience? Will this be a breaking change from a user flow or user experience perspective?_
No

**Comment by vibrantvarun** [comment]
@martin-gaievski @navneet1v thoughts on this ?

**Comment by martin-gaievski** [comment]
what's the behavior today for standard hybrid query if `trac_scores` flas is passed?

**Comment by vibrantvarun** [comment]
If track_scores is passed true or false, standard hybrid query does not have any impact. It is basically a blank placeholder in case of standard hybrid query

**Comment by martin-gaievski** [comment]
got it. did you have a chance to check what's the behavior for other queries (e.g. term or bool) when where is no sorting and `track_scores` is set?

**Comment by vibrantvarun** [comment]
Alright, I just checked the behavior of other queries and got to know that

For bool query also it is a placeholder and do not block this case. When sorting is applied in bool query and track_scores=false then results have null scores.

Same behavior with term query.


Therefore, I misunderstood the cx experience aspect. We do not need this.
