### ISSUE TITLE
[FEATURE] Refactor HybridQuery*Tests to decouple types from K-NN library

### ISSUE THREAD

**Issue by chishui** [opensearch-project/neural-search#859]
### Is your feature request related to a problem?
HybridQueryPhaseSearcherTests has direct references to types in K-NN library, and it has broken the build several times recently as k-NN repo keeps refactoring their code. While a [feature request ](https://github.com/opensearch-project/k-NN/issues/1860)was made to k-NN repo asking guarantee for backward compatibility, but there's no mechanism set up yet.

Broken test: 
1. https://github.com/opensearch-project/neural-search/actions/runs/10258762961/job/28382116242?pr=852
2. https://github.com/opensearch-project/neural-search/actions/runs/9904116192/job/27602462802?pr=832

### What solution would you like?
Can we refactor HybridQueryPhaseSearcherTests to make it not directly refer to those k-NN types?

### What alternatives have you considered?
k-NN repo to have a mechanism to ensure backward compatibility.

### Do you have any additional context?
NA

**Comment by martin-gaievski** [comment]
We should be able to refactor HybridQueryPhaseSearcherTests and get rid of KNN specific classes, in those test cases knn query isn't required and can be replaced by other core query.
But there are other tests where it's not trivial, like [HybridQueryTests](https://github.com/opensearch-project/neural-search/blob/main/src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java), where knn query is a must

**Comment by chishui** [comment]
neural-search [build failed ](https://github.com/opensearch-project/neural-search/actions/runs/10277413701/job/28443312436?pr=852)due to another [k-NN update](https://github.com/opensearch-project/k-NN/commit/df7627c6e580843beb2361f5c2ec3519efd52280#diff-d5240888e4ed8c6fb277d8b9b9fc1680f632535629ededfe04311303777f04ba).
