### ISSUE TITLE
[BUG] Nested field missing sub embedding field will cause the IndexOutOfBoundsException

### ISSUE THREAD

**Issue by wdongyu** [opensearch-project/neural-search#909]
### What is the bug?
Currently, if a nested field `nestedField` with two sub field `textField` and `textFieldNotForEmbedding`, and a doc like:

```
{
  "nestedField": [
    {
      "textFieldNotForEmbedding": "This is a text field"
    },
    {
      "textField": "This is another text field"
    }
  ]
}
```

applying pipeline configuration:

```
{
  "description": ...,
  "processors": [
    {
      "text_embedding": {
        "model_id": ...,
        "field_map": {
          "nestedField": {
              "textField": "vectorField"
          }
        }
      }
    }
  ]
}
```

Result:
```
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
```

Expected result:
```
{
  "nestedField": [
    {
      "textFieldNotForEmbedding": "This is a text field"
    },
    {
      "textField": "This is another text field"
      "vectorField": [...]
    }
  ]
}
```

### How can one reproduce the bug?
Change the mock doc in [test code](https://github.com/opensearch-project/neural-search/blob/main/src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java#L1032):
```
// textField --> textFieldNotForEmbedding

nestedObj1.put("textFieldNotForEmbedding", "This is a text field") 
```

In [unit test](https://github.com/opensearch-project/neural-search/blob/main/src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java#L728), get the nlpResult from `textEmbeddingProcessor.buildNLPResult`, then set it to each field in original doc just like the embedding processor actually does:
```
Map<String, Object> nlpResult = textEmbeddingProcessor.buildNLPResult(
            knnMap,
            modelTensorList,
            ingestDocument.getSourceAndMetadata()
        );
nlpResult.forEach(ingestDocument::setFieldValue);
```

And run the unit test with:
```
./gradlew ':test' --tests "org.opensearch.neuralsearch.processor.TextEmbeddingProcessorTests.testBuildVectorOutput_withNestedList_successful"
```

### What is the expected behavior?
Mentioned above.

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by wdongyu** [comment]
When [setting fields in IngestDocument](https://github.com/opensearch-project/neural-search/blob/main/src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java#L421), the processor should check if the textField is not empty :

```
// build nlp output for list of nested objects
for (Map<String, Object> nestedElement : (List<Map<String, Object>>) sourceAndMetadataMap.get(processorKey)) {
     // Adding non empty check for inputNestedMapEntry, Only fill in embedding when value is not null
     // if (inputNestedMapEntry.getValue().get(index) != null)
     nestedElement.put(inputNestedMapEntry.getKey(), results.get(indexWrapper.index++));
}
```

willing to open a pr if confirmed.

**Comment by vibrantvarun** [comment]
@martin-gaievski I think it is a bug and needs to be fixed. Can you once confirm?

**Comment by martin-gaievski** [comment]
yup, looks like it, we need a fix for it. @wdongyu is this on latest main and 2.x, or specific to a certain 2.x version?

**Comment by wdongyu** [comment]
@martin-gaievski I test on latest main, it should exist in all versions
