### ISSUE TITLE
[BUG] Code coverage event based report is disabled

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/neural-search#974]
### What is the bug?
Code coverage is broken for the repo. Report is showing some data, but [latest commit](https://app.codecov.io/gh/opensearch-project/neural-search/commit/7c54c86e256cfb43d0e7623bda1f7590c4a18b0e) that has been consumed is 6 months old: https://app.codecov.io/gh/opensearch-project/neural-search. Also recent PRs are missing this report, check out the most recent PR merged at time of writing https://github.com/opensearch-project/neural-search/pull/971

**Comment by yuye-aws** [comment]
The [PR](https://github.com/opensearch-project/neural-search/pull/975) has been merged. @martin-gaievski Can you check whether this issue has been resolved?

**Comment by martin-gaievski** [comment]
I want to keep this open for some time. I see for my PR coverage got updated, but one after PR has failed. Let's gather more info before we conclude if that is fixed or not

**Comment by martin-gaievski** [comment]
I'm seeing the coverage report got uploaded for some recent PRs (https://github.com/opensearch-project/neural-search/pull/978), I think we're good to close this issue
